favicon: favicon.ico
title: 彩銘羽のウェブサイト
description: 平凡な場所が、あなた方の関心を待ち望んでいる。
theme: jekyll-theme-merlot
url: https://www.caimingyu.tokyo
paginate: 10
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap